FROM node:latest

LABEL "com.github.actions.name"="GitHub Action for clasp"
LABEL "com.github.actions.description"="Clasp helper"
LABEL "com.github.actions.icon"="upload-cloud"
LABEL "com.github.actions.color"="blue"

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
